### ISSUE TITLE
Invalid/expired invite link for discord

### ISSUE THREAD

**Issue by DesolatePsyche** [seanbreckenridge/mal-notify-bot#2]
Invalid/expired invite link for discord

Want to use this feature/bot to get notified but can't join server. Please update link.

**Comment by purplepinapples** [comment]
Hi, sorry for taking so long to respond to this; I'm not sure whats going on.

The link on the README points to https://discordapp.com/invite/ajABjeN

which seems to be fine on my end:

<img width="760" alt="Screen Shot 2019-06-12 at 6 30 25 PM" src="https://user-images.githubusercontent.com/45589728/59397158-7319ba00-8d40-11e9-80bc-e32676c42ad3.png">

I can try creating a new invite link for you if thats not working, you can contact me at `PurplePinapples#3673` on discord.

**Comment by purplepinapples** [comment]
Updated README to make this less common
